//I copy pasted this code because I amazed by how below code automates CI/CD pipeline in effective way. original location of this yml is in 
//https://github.com/polkadot-js/extension/blob/master/.github/workflows/push-master.yml
//I appreciate how much YML automation power can be stretched to new boundaries
name: Master
on:
  push:
    branches:
      - master

/*jobs:
  master:
    if: "! startsWith(github.event.head_commit.message, '[CI Skip]')"
    strategy:
      matrix:
        step: ['build:release']
    name: ${{ matrix.step }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.GH_PAT }}
    - name: ${{ matrix.step }}
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        GH_PAT: ${{ secrets.GH_PAT }}
        GH_RELEASE_GITHUB_API_TOKEN: ${{ secrets.GH_PAT }}
        GH_RELEASE_FILES: master-build.zip,master-src.zip
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: |
        yarn install --immutable | grep -v 'YN0013'
        yarn ${{ matrix.step }}
*/
